#-----------------------------------------------------------------------
ICE_PATH  := /usr/share/Ice-3.4.2
BUILD_PATH := /home/jyk/workplace/util

APP       := MasterSrv
TARGET    := MasterSrv
MFLAGS    :=
CONFIG    := conf
STRIP_FLAG:= N
ICE_SLICE := /usr/share/Ice-3.4.2/slice

#-----------------------------------------------------------------------
INCLUDE   += -I/usr/include/Ice
LIB             +=  -llog4cplus

#-----------------------------------------------------------------------
include ${BUILD_PATH}/tool/utiltool.mk
include ${BUILD_PATH}/basic/makefile.jyk
#-----------------------------------------------------------------------
